

export const ACTIONS = {
    SET_TOOL: "SET_TOOL",
    SET_CANVAS: "SET_CANVAS",
    SET_FILL_COLOR: "SET_FILL_COLOR",
    SET_STROKE_COLOR: "SET_STROKE_COLOR",
    SET_WIDTH: "SET_WIDTH",
    PUSH_REDO: "PUSH_REDO",
    PUSH_UNDO: "PUSH_UNDO",
    UNDO:"UNDO",
    REDO:"REDO"
}